POST http://localhost:8765/hook
Content-Type: application/json
Accept: application/json
X-Gitee-Event: Merge Request Hook
X-Gitee-Token: Secret

{
  "action": "open",
  "action_desc": null,
  "pull_request": {
    "id": 3325576,
    "number": 23,
    "state": "open",
    "html_url": "https://gitee.com/open-euler/syncbot-example/pulls/23",
    "diff_url": "https://gitee.com/open-euler/syncbot-example/pulls/23.diff",
    "patch_url": "https://gitee.com/open-euler/syncbot-example/pulls/23.patch",
    "title": "remove bar.txt, add and update BAR.txt",
    "body": "https://gitee.com/open-euler/syncbot-example/issues/I29DVM\r\n\r\nhttps://gitee.com/open-euler/syncbot-example/issues/I29DVN\r\n",
    "labels": [

    ],
    "languages": [

    ],
    "created_at": "2021-01-05T17:25:43+08:00",
    "updated_at": "2021-01-05T17:25:43+08:00",
    "closed_at": null,
    "merged_at": null,
    "merge_commit_sha": null,
    "merge_reference_name": "refs/pull/23/MERGE",
    "user": {
      "id": 7400170,
      "name": "chenyanpanHW",
      "email": "chenyanpan@huawei.com",
      "username": "chenyanpanHW",
      "user_name": "chenyanpanHW",
      "url": "https://gitee.com/chenyanpanHW",
      "login": "chenyanpanHW",
      "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
      "html_url": "https://gitee.com/chenyanpanHW",
      "type": "User",
      "site_admin": false
    },
    "assignee": null,
    "assignees": [

    ],
    "tester": null,
    "testers": [

    ],
    "need_test": false,
    "need_review": false,
    "milestone": null,
    "head": {
      "label": "chenyanpanHW:bar",
      "ref": "bar",
      "sha": "1aa5862300fd359cae0bf740ba436be1313920f7",
      "user": {
        "id": 7400170,
        "name": "chenyanpanHW",
        "email": "chenyanpan@huawei.com",
        "username": "chenyanpanHW",
        "user_name": "chenyanpanHW",
        "url": "https://gitee.com/chenyanpanHW",
        "login": "chenyanpanHW",
        "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
        "html_url": "https://gitee.com/chenyanpanHW",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 12940324,
        "name": "syncbotExample",
        "path": "syncbot-example",
        "full_name": "chenyanpanHW/syncbot-example",
        "org": {
          "id": 7400170,
          "name": "chenyanpanHW",
          "email": "chenyanpan@huawei.com",
          "username": "chenyanpanHW",
          "user_name": "chenyanpanHW",
          "url": "https://gitee.com/chenyanpanHW",
          "login": "chenyanpanHW",
          "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
          "html_url": "https://gitee.com/chenyanpanHW",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://gitee.com/chenyanpanHW/syncbot-example",
        "url": "https://gitee.com/chenyanpanHW/syncbot-example",
        "description": "syncbot-example 示例",
        "fork": true,
        "created_at": "2020-11-27T11:28:36+08:00",
        "updated_at": "2020-12-30T15:48:51+08:00",
        "pushed_at": "2020-12-30T15:48:51+08:00",
        "git_url": "git://gitee.com/chenyanpanHW/syncbot-example.git",
        "ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
        "clone_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
        "svn_url": "svn://gitee.com/chenyanpanHW/syncbot-example",
        "git_http_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
        "git_ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
        "git_svn_url": "svn://gitee.com/chenyanpanHW/syncbot-example",
        "homepage": null,
        "stargazers_count": 0,
        "watchers_count": 1,
        "forks_count": 0,
        "language": "other",
        "has_issues": true,
        "has_wiki": true,
        "has_pages": false,
        "license": "MulanPSL-2.0",
        "open_issues_count": 0,
        "default_branch": "master",
        "namespace": "chenyanpanHW",
        "name_with_namespace": "chenyanpanHW/syncbotExample",
        "path_with_namespace": "chenyanpanHW/syncbot-example"
      }
    },
    "base": {
      "label": "openEuler:master",
      "ref": "master",
      "sha": "709d687d076605d4b63d19fffccf00807ca800e4",
      "user": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "repo": {
        "id": 12940005,
        "name": "syncbotExample",
        "path": "syncbot-example",
        "full_name": "open-euler/syncbot-example",
        "org": {
          "id": 341810,
          "name": "syncBot",
          "email": "custa@126.com",
          "username": "sync-bot",
          "user_name": "sync-bot",
          "url": "https://gitee.com/sync-bot",
          "login": "sync-bot",
          "avatar_url": "https://gitee.com/assets/no_portrait.png",
          "html_url": "https://gitee.com/sync-bot",
          "type": "User",
          "site_admin": false
        },
        "private": false,
        "html_url": "https://gitee.com/open-euler/syncbot-example",
        "url": "https://gitee.com/open-euler/syncbot-example",
        "description": "syncbot-example 示例",
        "fork": false,
        "created_at": "2020-11-27T11:18:01+08:00",
        "updated_at": "2021-01-05T17:23:41+08:00",
        "pushed_at": "2020-12-25T20:49:19+08:00",
        "git_url": "git://gitee.com/open-euler/syncbot-example.git",
        "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
        "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
        "svn_url": "svn://gitee.com/open-euler/syncbot-example",
        "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
        "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
        "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
        "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
        "stargazers_count": 0,
        "watchers_count": 2,
        "forks_count": 1,
        "language": "other",
        "has_issues": true,
        "has_wiki": true,
        "has_pages": false,
        "license": "MulanPSL-2.0",
        "open_issues_count": 2,
        "default_branch": "master",
        "namespace": "open-euler",
        "name_with_namespace": "openEuler/syncbotExample",
        "path_with_namespace": "open-euler/syncbot-example"
      }
    },
    "merged": false,
    "mergeable": true,
    "merge_status": "unchecked",
    "updated_by": {
      "id": 7400170,
      "name": "chenyanpanHW",
      "email": "chenyanpan@huawei.com",
      "username": "chenyanpanHW",
      "user_name": "chenyanpanHW",
      "url": "https://gitee.com/chenyanpanHW",
      "login": "chenyanpanHW",
      "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
      "html_url": "https://gitee.com/chenyanpanHW",
      "type": "User",
      "site_admin": false
    },
    "comments": 0,
    "commits": 6,
    "additions": 1,
    "deletions": 38,
    "changed_files": 4
  },
  "number": 23,
  "iid": 23,
  "title": "remove bar.txt, add and update BAR.txt",
  "body": "https://gitee.com/open-euler/syncbot-example/issues/I29DVM\r\n\r\nhttps://gitee.com/open-euler/syncbot-example/issues/I29DVN\r\n",
  "languages": [

  ],
  "state": "open",
  "merge_status": "unchecked",
  "merge_commit_sha": null,
  "url": "https://gitee.com/open-euler/syncbot-example/pulls/23",
  "source_branch": "bar",
  "source_repo": {
    "project": {
      "id": 12940324,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "chenyanpanHW/syncbot-example",
      "org": {
        "id": 7400170,
        "name": "chenyanpanHW",
        "email": "chenyanpan@huawei.com",
        "username": "chenyanpanHW",
        "user_name": "chenyanpanHW",
        "url": "https://gitee.com/chenyanpanHW",
        "login": "chenyanpanHW",
        "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
        "html_url": "https://gitee.com/chenyanpanHW",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/chenyanpanHW/syncbot-example",
      "url": "https://gitee.com/chenyanpanHW/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": true,
      "created_at": "2020-11-27T11:28:36+08:00",
      "updated_at": "2020-12-30T15:48:51+08:00",
      "pushed_at": "2020-12-30T15:48:51+08:00",
      "git_url": "git://gitee.com/chenyanpanHW/syncbot-example.git",
      "ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
      "clone_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "svn_url": "svn://gitee.com/chenyanpanHW/syncbot-example",
      "git_http_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
      "git_svn_url": "svn://gitee.com/chenyanpanHW/syncbot-example",
      "homepage": null,
      "stargazers_count": 0,
      "watchers_count": 1,
      "forks_count": 0,
      "language": "other",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 0,
      "default_branch": "master",
      "namespace": "chenyanpanHW",
      "name_with_namespace": "chenyanpanHW/syncbotExample",
      "path_with_namespace": "chenyanpanHW/syncbot-example"
    },
    "repository": {
      "id": 12940324,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "chenyanpanHW/syncbot-example",
      "org": {
        "id": 7400170,
        "name": "chenyanpanHW",
        "email": "chenyanpan@huawei.com",
        "username": "chenyanpanHW",
        "user_name": "chenyanpanHW",
        "url": "https://gitee.com/chenyanpanHW",
        "login": "chenyanpanHW",
        "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
        "html_url": "https://gitee.com/chenyanpanHW",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/chenyanpanHW/syncbot-example",
      "url": "https://gitee.com/chenyanpanHW/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": true,
      "created_at": "2020-11-27T11:28:36+08:00",
      "updated_at": "2020-12-30T15:48:51+08:00",
      "pushed_at": "2020-12-30T15:48:51+08:00",
      "git_url": "git://gitee.com/chenyanpanHW/syncbot-example.git",
      "ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
      "clone_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "svn_url": "svn://gitee.com/chenyanpanHW/syncbot-example",
      "git_http_url": "https://gitee.com/chenyanpanHW/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:chenyanpanHW/syncbot-example.git",
      "git_svn_url": "svn://gitee.com/chenyanpanHW/syncbot-example",
      "homepage": null,
      "stargazers_count": 0,
      "watchers_count": 1,
      "forks_count": 0,
      "language": "other",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 0,
      "default_branch": "master",
      "namespace": "chenyanpanHW",
      "name_with_namespace": "chenyanpanHW/syncbotExample",
      "path_with_namespace": "chenyanpanHW/syncbot-example"
    }
  },
  "target_branch": "master",
  "target_repo": {
    "project": {
      "id": 12940005,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "open-euler/syncbot-example",
      "org": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/open-euler/syncbot-example",
      "url": "https://gitee.com/open-euler/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": false,
      "created_at": "2020-11-27T11:18:01+08:00",
      "updated_at": "2021-01-05T17:23:41+08:00",
      "pushed_at": "2020-12-25T20:49:19+08:00",
      "git_url": "git://gitee.com/open-euler/syncbot-example.git",
      "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
      "svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
      "stargazers_count": 0,
      "watchers_count": 2,
      "forks_count": 1,
      "language": "other",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 2,
      "default_branch": "master",
      "namespace": "open-euler",
      "name_with_namespace": "openEuler/syncbotExample",
      "path_with_namespace": "open-euler/syncbot-example"
    },
    "repository": {
      "id": 12940005,
      "name": "syncbotExample",
      "path": "syncbot-example",
      "full_name": "open-euler/syncbot-example",
      "org": {
        "id": 341810,
        "name": "syncBot",
        "email": "custa@126.com",
        "username": "sync-bot",
        "user_name": "sync-bot",
        "url": "https://gitee.com/sync-bot",
        "login": "sync-bot",
        "avatar_url": "https://gitee.com/assets/no_portrait.png",
        "html_url": "https://gitee.com/sync-bot",
        "type": "User",
        "site_admin": false
      },
      "private": false,
      "html_url": "https://gitee.com/open-euler/syncbot-example",
      "url": "https://gitee.com/open-euler/syncbot-example",
      "description": "syncbot-example 示例",
      "fork": false,
      "created_at": "2020-11-27T11:18:01+08:00",
      "updated_at": "2021-01-05T17:23:41+08:00",
      "pushed_at": "2020-12-25T20:49:19+08:00",
      "git_url": "git://gitee.com/open-euler/syncbot-example.git",
      "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
      "svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
      "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
      "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
      "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
      "stargazers_count": 0,
      "watchers_count": 2,
      "forks_count": 1,
      "language": "other",
      "has_issues": true,
      "has_wiki": true,
      "has_pages": false,
      "license": "MulanPSL-2.0",
      "open_issues_count": 2,
      "default_branch": "master",
      "namespace": "open-euler",
      "name_with_namespace": "openEuler/syncbotExample",
      "path_with_namespace": "open-euler/syncbot-example"
    }
  },
  "project": {
    "id": 12940005,
    "name": "syncbotExample",
    "path": "syncbot-example",
    "full_name": "open-euler/syncbot-example",
    "org": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://gitee.com/open-euler/syncbot-example",
    "url": "https://gitee.com/open-euler/syncbot-example",
    "description": "syncbot-example 示例",
    "fork": false,
    "created_at": "2020-11-27T11:18:01+08:00",
    "updated_at": "2021-01-05T17:23:41+08:00",
    "pushed_at": "2020-12-25T20:49:19+08:00",
    "git_url": "git://gitee.com/open-euler/syncbot-example.git",
    "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
    "svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
    "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
    "stargazers_count": 0,
    "watchers_count": 2,
    "forks_count": 1,
    "language": "other",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "license": "MulanPSL-2.0",
    "open_issues_count": 2,
    "default_branch": "master",
    "namespace": "open-euler",
    "name_with_namespace": "openEuler/syncbotExample",
    "path_with_namespace": "open-euler/syncbot-example"
  },
  "repository": {
    "id": 12940005,
    "name": "syncbotExample",
    "path": "syncbot-example",
    "full_name": "open-euler/syncbot-example",
    "org": {
      "id": 341810,
      "name": "syncBot",
      "email": "custa@126.com",
      "username": "sync-bot",
      "user_name": "sync-bot",
      "url": "https://gitee.com/sync-bot",
      "login": "sync-bot",
      "avatar_url": "https://gitee.com/assets/no_portrait.png",
      "html_url": "https://gitee.com/sync-bot",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://gitee.com/open-euler/syncbot-example",
    "url": "https://gitee.com/open-euler/syncbot-example",
    "description": "syncbot-example 示例",
    "fork": false,
    "created_at": "2020-11-27T11:18:01+08:00",
    "updated_at": "2021-01-05T17:23:41+08:00",
    "pushed_at": "2020-12-25T20:49:19+08:00",
    "git_url": "git://gitee.com/open-euler/syncbot-example.git",
    "ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "clone_url": "https://gitee.com/open-euler/syncbot-example.git",
    "svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "git_http_url": "https://gitee.com/open-euler/syncbot-example.git",
    "git_ssh_url": "git@gitee.com:open-euler/syncbot-example.git",
    "git_svn_url": "svn://gitee.com/open-euler/syncbot-example",
    "homepage": "https://gitee.com/open-euler/syncbot-example/homepage",
    "stargazers_count": 0,
    "watchers_count": 2,
    "forks_count": 1,
    "language": "other",
    "has_issues": true,
    "has_wiki": true,
    "has_pages": false,
    "license": "MulanPSL-2.0",
    "open_issues_count": 2,
    "default_branch": "master",
    "namespace": "open-euler",
    "name_with_namespace": "openEuler/syncbotExample",
    "path_with_namespace": "open-euler/syncbot-example"
  },
  "author": {
    "id": 7400170,
    "name": "chenyanpanHW",
    "email": "chenyanpan@huawei.com",
    "username": "chenyanpanHW",
    "user_name": "chenyanpanHW",
    "url": "https://gitee.com/chenyanpanHW",
    "login": "chenyanpanHW",
    "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
    "html_url": "https://gitee.com/chenyanpanHW",
    "type": "User",
    "site_admin": false
  },
  "updated_by": {
    "id": 7400170,
    "name": "chenyanpanHW",
    "email": "chenyanpan@huawei.com",
    "username": "chenyanpanHW",
    "user_name": "chenyanpanHW",
    "url": "https://gitee.com/chenyanpanHW",
    "login": "chenyanpanHW",
    "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
    "html_url": "https://gitee.com/chenyanpanHW",
    "type": "User",
    "site_admin": false
  },
  "sender": {
    "id": 7400170,
    "name": "chenyanpanHW",
    "email": "chenyanpan@huawei.com",
    "username": "chenyanpanHW",
    "user_name": "chenyanpanHW",
    "url": "https://gitee.com/chenyanpanHW",
    "login": "chenyanpanHW",
    "avatar_url": "https://portrait.gitee.com/uploads/avatars/user/2466/7400170_chenyanpanHW_1604646878.png",
    "html_url": "https://gitee.com/chenyanpanHW",
    "type": "User",
    "site_admin": false
  },
  "target_user": null,
  "enterprise": null,
  "hook_name": "merge_request_hooks",
  "hook_id": 512083,
  "hook_url": "https://gitee.com/open-euler/syncbot-example/hooks/512083/edit",
  "password": "Secret",
  "timestamp": "1609838744342",
  "sign": ""
}
